### ISSUE TITLE
gitEnv fails outside of repo

### ISSUE THREAD

**Issue by bengranett** [didamarkovic/metafil#1]
`gitEnv` fails to return the commit info when working outside of a repo.  Ideally it would return the commit of the package of interest, eg the version of [code] that is running.  I don't have a suggestion of how to implement this though...

**Comment by didamarkovic** [comment]
Hi @bengranett, commit e22df2531bc should have fixed that, so that now it only returns time, date, path and username info in the case no `.git` folder is in the nearby path. I think guessing the version of the parent code will have to be dealt with otherwise.

**Comment by didamarkovic** [comment]
I think this is more-or-less fixed by commit ae1a28b71a4f5. If you pass the name of your installation to the `GitEnv` class at initialisation, it looks up the version set in the `setup.py` file.
